### ISSUE TITLE
GstFileSinkBufferMode implementation in Golang

### ISSUE THREAD

**Issue by danijelk00** [go-gst/go-gst#154] opened 2024-12-11 10:35 UTC
Hello,

I wonder if there is an implementation for the GstFileSinkBufferMode structure in Golang?
I am trying to set the "buffer-mode" property for the filesink element, however the property type is defined as GstFileSinkBufferMode, which has no implementation in Golang.
I am wondering if there is an alternative to solve this problem?
I have tried using the values ​​0,1,2 directly as well as the string values, however I get an error message every time.

```
File-sink-buffer-mode 
File read buffering mode.
Members
default (-1) – Default buffering
full (0) – Fully buffered
line (1) – Line buffered (deprecated, like full)
unbuffered (2) – Unbuffered
```

**Comment by RSWilli** [comment] 2024-12-11 14:40
this is a duplicate of #104 

Currently you can use the integer values of the enum to set the property with `SetProperty` or the string name with `SetArg`

If you have an idea how this can be solved then continue in #104 please

**Closed by RSWilli** 2024-12-11 14:40 UTC
Labels: documentation
