### ISSUE TITLE
How to setup autovideosink sync=false

### ISSUE THREAD

**Issue by joyhope** [go-gst/go-gst#93] opened 2024-06-14 02:51 UTC
My pipeline is setup as

	pipeline, err := gst.NewPipeline("")
	if err != nil {
		return nil, nil, err
	}

	// Create the elements
	elems, err := gst.NewElementMany("appsrc", "queue", "h264parse", "avdec_h264", "autovideosink")
	if err != nil {
		return nil, nil, err
	}

	// Add the elements to the pipeline and link them
	pipeline.AddMany(elems...)
	gst.ElementLinkMany(elems...)

but I tried many ways to setup sync=false to the autovidosink,  it passed compile but reported a link error (-1)  

There are many ways to construct the pipeline, but I am still unable to find a common way.

**Comment by joyhope** [comment] 2024-06-14 03:18
I changed to this
	elems, err := gst.NewElementMany("appsrc", "queue", "h264parse", "avdec_h264")
	if err != nil {
		return nil, nil, err
	}

	sink, err := gst.NewElementWithProperties("autovideosink", map[string]interface{}{
		"sync": false,
	})
	if err != nil {
		return nil, nil, err
	}
	elems=append(elems, sink)
	// Add the elements to the pipeline and link them
	pipeline.AddMany(elems...)
	gst.ElementLinkMany(elems...)

It seems no runtime error, is there any suggested solution?

**Comment by joyhope** [comment] 2024-06-14 07:36
It seems pass compile, but with the runtime result, I think the sync=false is not properly setup in the autovideosink.

**Comment by RSWilli** [comment] 2024-06-14 07:49
`NewElementMany` and `NewElementWithProperties` should both work. When using `NewElementMany` you need to call `SetProperty` on the correct element to set `sync`.

> I think the sync=false is not properly setup in the autovideosink.

To verify this you could use the debugging tool supplied by gstreamer:

* https://gstreamer.freedesktop.org/documentation/gstreamer/debugutils.html?gi-language=c
* https://gstreamer.freedesktop.org/documentation/tutorials/basic/debugging-tools.html?gi-language=c

**Comment by joyhope** [comment] 2024-06-14 14:48
I have not used the debug tool to confirm.  The result is the same whatever the sync=true/false.  In a pure C environment, I could confirm the syn=false will be faster.  

I tried to make it as low latency as possible, so I needed to set sync to false, but I did not find any result different.  It is strange.

**Comment by RSWilli** [comment] 2024-06-14 15:03
This sounds like your use case is better suited by https://gstreamer.freedesktop.org/documentation/additional/design/gstpipeline.html?gi-language=c

> The _use_clock() method forces the use of a specific clock on the pipeline regardless of what clock providers are available. Passing a NULL GstClock *clock parameter to this method disables all clocking and makes the pipeline run as fast as possible.

Use clock is called `ForceClock` in `go-gst`, we should probably rename that :)

Please note that neither clock selection nor the `sync` property can or will influence the latency of your pipeline.

If you have any gstreamer specific questions, those are better asked at https://discourse.gstreamer.org/ . Please use the issues in `go-gst` for golang binding specific questions

**Comment by joyhope** [comment] 2024-06-16 14:04
>>Please note that neither clock selection nor the sync property can or will influence the latency of your pipeline.
My case is appsrc.  In C environment, sync=true  will cause 150ms delay, but sync=false will cause only <50ms delay. 

I think I wrote the same pipeline in go-gst.  But I did not know why, go-gst caused 500ms delay.

Only two points different from C is
1.  xxx_use_clock.  (In C, if  does not call this, the C pipeline is failure to work, but go-gst won't.)
2. In C: syn=true/false will be easy to see the latency changed, but go-gst is nothing changed. 

I have not find where is the problem in go-gst.    go-gst is very easy to use,  but the latency problem is stranged.

**Comment by joyhope** [comment] 2024-06-16 14:20
How could I confirm the sync=false is success setup? I use GST_DEBUG=4,  but there is no such setup information.

**Comment by joyhope** [comment] 2024-06-16 14:26
In this: https://gstreamer.freedesktop.org/documentation/base/gstbasesink.html?gi-language=c

Configures sink to synchronize on the clock or not. When sync is FALSE, incoming samples will be played as fast as possible. If sync is TRUE, the timestamps of the incoming buffers will be used to schedule the exact render time of its contents.

autovideosink is not from the base-sink,   The setproperty is not sure worked.

**Comment by joyhope** [comment] 2024-06-16 14:49
May be no related with sync=true/false,  the slow is coming from go-gst message loop?  I just copy the go-gst/example/common.go,  Whether the loop solution is a little more complex (slow) than the pure C solution.

**Comment by joyhope** [comment] 2024-06-17 06:29
I use GST_DEBUG=4 , and compare the C and go-gst log output, but find one output only happened in go-gst 

0:00:00.087917122 70627       0xc0d760 INFO                   libav :0:: Requested frame threading with a custom get_buffer2() implementation which is not marked as thread safe. This is not supported anymore, make your callback thread-safe.

I isolate the related log: 

In C output: 

0:00:06.863326282 70292 0x5f08d756b300 INFO                   libav gstavcodecmap.c:2687:gst_ffmpeg_caps_to_pixfmt: ignoring framerate 0/1 (probably variable framerate)
0:00:06.864125783 70292 0x5f08d756b300 INFO               videometa gstvideometa.c:1072:gst_video_time_code_meta_api_get_type: registering

In go-gst output
0:00:32.696139766 70627       0xc0d760 INFO                   libav gstavcodecmap.c:2687:gst_ffmpeg_caps_to_pixfmt: ignoring framerate 0/1 (probably variable framerate)
0:00:32.696184456 70627       0xc0d760 INFO                   libav :0:: Requested frame threading with a custom get_buffer2() implementation which is not marked as thread safe. This is not supported anymore, make your callback thread-safe.
0:00:32.696853886 70627       0xc0d760 INFO               videometa gstvideometa.c:1072:gst_video_time_code_meta_api_get_type: registering


I seems go-gst some callback implement use different method?  

Is there any suggestion?

**Comment by joyhope** [comment] 2024-06-17 06:37
In C environment 

g_object_set(renderer->appsrc, "caps", caps, "stream-type", 0, "is-live", TRUE, "format", GST_FORMAT_TIME, NULL);

In go-gst

	src.SetCaps(caps)
	liveval, err:=glib.GValue(true)
	if err != nil {
		return nil, nil, err
	}
	src.SetProperty("is-live", liveval)
	src.SetProperty("format", gst.FormatTime)

but in the log 
C:  0:00:00.066172081 70292 0x5f08d7286400 INFO                pipeline gstpipeline.c:533:gst_pipeline_change_state:<pipeline0> pipeline is live

go-gst:  0:00:00.087298406 70627       0x98f0c0 INFO                pipeline gstpipeline.c:533:gst_pipeline_change_state:<pipeline0> pipeline is not live

It seems the property set live is not function.  If this is true, the sync=true will meet similar problem.

**Comment by joyhope** [comment] 2024-06-17 07:04
My question: C always uses g_boject_set this API, but go-gst never uses this low-level API.

**Comment by joyhope** [comment] 2024-06-17 07:30
I confirmed the slow (long latency) is coming from is-live.  In C, I disable the property, the latency is the same as go-gst.  So go-gst is-live setup is not working. 

How could I setup the is-live in go-gst?

**Comment by RSWilli** [comment] 2024-06-17 11:26
> My question: C always uses g_boject_set this API, but go-gst never uses this low-level API.

go-gst uses [g_object_set_property](https://github.com/go-gst/go-glib/blob/main/glib/gobject.go#L235) under the hood if you use `SetProperty`. This should work the same AFAIK.

**Comment by RSWilli** [comment] 2024-06-17 11:28
> May be no related with sync=true/false, the slow is coming from go-gst message loop? I just copy the go-gst/example/common.go, Whether the loop solution is a little more complex (slow) than the pure C solution. (This is pure guess, I do not have any evidence.)

There is some overhead that you can expect when switching between go and c, especially in callbacks etc. This happens because of the stack switching. That said, this should not impact the latency of your pipeline AFAIK.

**Comment by joyhope** [comment] 2024-06-17 13:44
This works. 
	src.Set("is-live", true)    <<== go-glib api is called
But
	gval, err:=glib.GValue(true)
	if err != nil {
		return nil, nil, err
	}
       src.SetPropety("is-live", gval)  does not work. 

My problem is solved.  

But I want to clear the Set, SetPrroperty .  When to use.

**Comment by RSWilli** [comment] 2024-06-17 14:05
I cannot answer your question without a broader context of what you are doing, and some more of the surrounding code.

**Comment by RSWilli** [comment] 2024-06-17 14:11
> src.Set("is-live", true) <<== go-glib api is called

`src.Set` is [just an alias for the `SetProperty`](https://github.com/go-gst/go-glib/blob/main/glib/gobject.go#L172). You should call `SetProperty` the same way. Otherwise you will get a GValue wrapping a GValue containing a boolean or similar.

As the docs state:

> [SetProperty] attempts to convert the given Go value to a GValue before setting the property.

so

```
 src.SetPropety("is-live", true)
```

should also do the job.

**Comment by RSWilli** [comment] 2024-06-17 14:13
If you for some reason need the GValue beforehand, then `SetPropertyValue` is your friend. It is called internally by `SetProperty` after converting to a GValue

**Comment by joyhope** [comment] 2024-06-17 14:26
I will study the SetProperty.   Many thanks.

**Comment by RSWilli** [comment] 2024-06-17 15:45
Closing since working as intended

**Closed by RSWilli** 2024-06-17 15:45 UTC
