### ISSUE TITLE
Not an issue but a request for more examples

### ISSUE THREAD

**Issue by SonnyWalkman** [go-gst/go-gst#73] opened 2024-04-06 11:56 UTC
Hello,
I was hoping for a few more examples with attaching signals.
I'm using  this pipeline.  `"uridecodebin3 name=source ! audioconvert ! volume name=vol ! autoaudiosink"  ` 

Note ** later the autoaudiosink is to be substituted with ! queue ! tee to attach to another running pipeline.   

basically I'm attempting a one-shot player for effects sounds.

I'm using the '"about-to-finish" signal to  seek back to start after setting the pipeline to pause the setting back to playing. However, using this signal cuts the audio short be a few seconds which indicates the end of filling the buffer.
Is there any method to keep the pipeline active without EOS?  I guess rebuiling the pipeline is one example however I feel this is a work around an obvious use of signals and pad probe, re-linking? elements in the pipeline.

 In addition, another example worth considering is the  rtmp2sink element?
Works great on local LAN however, streaming on WAN the where network disconnections are common the pipeline crashes. Is there a method to monitor in ago routine for network error  message and reconnect the  rtmp2sink element and restart after X seconds/minutes after the error has occurred.

There is an example in python for the rtmp2sink however, go is the go!  

[restart rtmp2sink](https://stackoverflow.com/questions/27905606/gstreamer-how-recover-from-rtmpsink-error/27924950#27924950)

Many Thanks

**Comment by RSWilli** [comment] 2024-04-06 15:15
Adding more examples would be a good thing, but since I personally only use a small subset of gstreamer features, I have no way of testing all these examples. 

IMHO the examples in `go-gst` should show the basic functionalities of how to use gstreamer in golang, but when it comes to specific functionalities of one (of the [many](https://gstreamer.freedesktop.org/documentation/plugins_doc.html?gi-language=c)) plugins of gstreamer, it is better to find the documentation in C (or python, or any other binding) and port them over to `go-gst`.

For most of the functionality, this should be pretty straight forward though.

**Comment by RSWilli** [comment] 2024-04-07 18:14
Regarding your question related to signnals: signals are a `glib` feature, so the docs for this live in the [`go-glib` godocs](https://pkg.go.dev/github.com/go-gst/go-glib@v1.0.0/glib#Object.Connect). It should be pretty straight forward to port any other bindings code.

> Is there any method to keep the pipeline active without EOS?

This however is a gstreamer specific question best asked in the [gstreamer discourse](https://discourse.gstreamer.org/)

> In addition, another example worth considering is the rtmp2sink element?

As said before, since I cannot test it properly because I lack the use cases, I cannot do this. If you figure out your problem though I would be happy to merge a PR if you create one.

**Comment by SonnyWalkman** [comment] 2024-04-11 09:39
Thanks @RSWilli , after a few hours poking around the examples and the c bindings I've managed to get a couple of my problems sorted.  However, jump one wall and see another. Today I began converting some input (source) pipelines into bins  gst.Bin (source bin) with video and audio pads. I have another bin operating with a compositor and a audiomixer and created ghost pads from the source to sink_%u but unfortunately just couldn't get the source to link to the bin. I've put the source set to ready and synced with parent. I'll think about it some more. 

The bin example didn't provide and ghost pad solution.

Thanks anyway.

**Comment by RSWilli** [comment] 2024-04-11 10:50
@SonnyWalkman unfortunately, this is the same experience I had when I first used the go gstreamer bindings. The problem is that (even though golang is simple and the bindings remove a lot of the need for manual memory management of every gstreamer ressource) gstreamer and more generally multimedia is not an easy topic. There are a lot of fundamental gstreamer concepts you need to understand to even use the core of gstreamer and after that you must understand the plugins you will use.

IMHO the function names are clear enough to convert an official c example to go-gst.

I'll close this issue  then.

P.S.: regarding your issue with ghost pads maybe this can help: https://gstreamer.freedesktop.org/documentation/application-development/basics/pads.html?gi-language=c#ghost-pads

Also you can set the `GST_DEBUG` env var to get better logs from gstreamer as documented in https://gstreamer.freedesktop.org/documentation/tutorials/basic/debugging-tools.html?gi-language=c . If this doesn't help consider asking a question in the [gstreamer discourse](https://discourse.gstreamer.org/)

**Closed by RSWilli** 2024-04-11 10:50 UTC
Labels: documentation
